services:
  - docker

before_install:
  - docker pull alpine

script:
  - docker build --no-cache -t graffic/logrotate .

deploy:
  provider: script
  script: bash deploy.sh
  on:
    tags: true
    
  
