env:
  global:
    - IMAGE_NAME=graffic/logrotate
services:
  - docker

script:
  - docker build --no-cache -t $IMAGE_NAME .

deploy:
  provider: script
  script: bash deploy.sh $IMAGE_NAME $TRAVIS_TAG
  on:
    tags: true
    
  
