version: "3"

services:
  logger:
    image: busybox
    command:
    - /bin/sh
    - -c
    - |
      while true
      do
        echo "[`date`] DEBUG `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1`" >> /logs/date.log
        sleep 1
      done
    volumes:
    - logs:/logs

  logrotate:
    build: "."
    environment:
      CRON_SCHEDULE: "* * * * *"
      LOGROTATE_PATTERN: "/logs/*.log"

    volumes:
    - logs:/logs

volumes:
  logs:
